"""
Django settings for CRMsystem project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from os.path import join

from CRMsystem.core import middleware

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_w$j4utyx0ey9c%4^9tyu2=v37r#($wk5n!1*14r^s=t%+cvl5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
INTERNAL_IPS = ('195.149.108.37',)
ALLOWED_HOSTS = []


# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup',
    'crm',
    'debug_toolbar',
    'rest_framework',
    #'django_cron',
    'django_crontab',
]

DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": lambda request: True,
}

#CRON_CLASSES = [
   # 'crm.cron.MyCronJob',
#]

#CRONJOBS = [
    #('5 * * * *', 'crm.cron.MyCronJob')
#]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    'CRMsystem.core.middleware.FirstMiddleware'
]

ROOT_URLCONF = 'CRMsystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CRMsystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators
AUTH_USER_MODEL = 'crm.Employer'
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

#CACHES = {
    #'default': {
    #    'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
    #    'LOCATION': os.path.join(BASE_DIR, 'django_cache'),
    #}
#}
# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

MEDIA_URL = "/media/"

STATIC_ROOT = os.path.join(BASE_DIR, "static")

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, "templates", "static"),
]

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

LOGIN_URL = 'login'


EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'yukiroakayoru@gmail.com'
EMAIL_HOST_PASSWORD = 'jedkrllfupxkrgke'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

PERMISSIONS = [
    ['company.list', 'Доступ к списку компаний'],
    ['company.employer', 'Доступ к списку сотрудников'],
    ['company.client', 'Доступ к списку клиентов'],
    ['company.department', 'Доступ к списку департамента'],
    ['company.notification', 'Доступ к списку новостей'],
    ['company.payment', 'Доступ к списку способов оплаты'],
    ['company.tour', 'Доступ к списку туров'],
    ['company.country', 'Доступ к списку стран'],
]

REDIS_HOST = 'localhost'
REDIS_PORT = 6379

#CACHES = {
    #'default': {
        #'BACKEND': 'django_redis.cache.RedisCache',
        #'LOCATION': 'redis://127.0.0.1:6379/',
        #'OPTIONS': {
         #   'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        #}
    #}
#}
