# Generated by Django 3.0.8 on 2020-07-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Company'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='date_joined',
            field=models.DateField(help_text='yyyy-mm-dd'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Department'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
