# Generated by Django 3.0.8 on 2020-07-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20200722_0719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={},
        ),
        migrations.AlterModelManagers(
            name='employer',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='employer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='employer',
            name='date_joined',
            field=models.DateField(help_text='yyyy-mm-dd'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employer',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employer',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='employer',
            name='last_login',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employer',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employer',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='employer',
            name='permission',
            field=models.CharField(choices=[['company.list', 'Доступ к списку компаний'], ['company.employer', 'Доступ к списку сотрудников'], ['company.client', 'Доступ к списку клиентов'], ['company.department', 'Доступ к списку департамента'], ['company.notification', 'Доступ к списку новостей'], ['company.payment', 'Доступ к списку способов оплаты'], ['company.tour', 'Доступ к списку туров'], ['company.country', 'Доступ к списку стран']], max_length=100),
        ),
        migrations.AlterField(
            model_name='employer',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
