# Generated by Django 3.0.8 on 2020-07-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20200723_0708'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employer',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='employer',
            name='permission',
            field=models.CharField(choices=[['company.list', 'Доступ к списку компаний'], ['company.employer', 'Доступ к списку сотрудников'], ['company.client', 'Доступ к списку клиентов'], ['company.department', 'Доступ к списку департамента'], ['company.notification', 'Доступ к списку новостей'], ['company.payment', 'Доступ к списку способов оплаты'], ['company.tour', 'Доступ к списку туров'], ['company.country', 'Доступ к списку стран']], default=None, max_length=100),
        ),
    ]
