# Generated by Django 3.0.8 on 2020-07-24 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20200723_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Company'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='department',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Department'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='language',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employer',
            name='passport',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='employer',
            name='permission',
            field=models.CharField(blank=True, choices=[['company.list', 'Доступ к списку компаний'], ['company.employer', 'Доступ к списку сотрудников'], ['company.client', 'Доступ к списку клиентов'], ['company.department', 'Доступ к списку департамента'], ['company.notification', 'Доступ к списку новостей'], ['company.payment', 'Доступ к списку способов оплаты'], ['company.tour', 'Доступ к списку туров'], ['company.country', 'Доступ к списку стран']], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
