# Generated by Django 3.0.8 on 2020-07-24 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20200724_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Company'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Department'),
        ),
    ]
