# Generated by Django 3.0.8 on 2020-07-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20200728_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='is_confirm',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
