# Generated by Django 3.0.8 on 2020-07-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_employer_is_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='permission',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
